server:
  port: 8861
eureka:
  client:
    service-url: http://127.0.0.1:8761/eureka/
spring:
  application:
    name: pc
mybatis:
  configLocation: mybatis/mybatis-config.xml
  mapperLocations: classpath*:mybatis*/**/*Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.stdout.StdOutImpl
